### ISSUE TITLE
linux提示List<>错误

### ISSUE THREAD

**Issue by wenfxl** [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin#1]
2023-03-15 08:00:26.7312| WARN|0|Plugin.PrepareSource Plugin "yunplugin.cs" [0] compiler notifications:
Error L3/C18: The type or namespace name 'Json' does not exist in the namespace 'System.Text' (are you missing an assembly reference?)
Error L1523/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)

**Comment by ZHANGTIANYAO1** [comment]
这个应该是TS3AUDIOBOT官方的那个的编译问题，等一下我会把我自己编译的打包上传。

**Comment by ZHANGTIANYAO1** [comment]
或者你可以尝试按照官方的wiki自己本地编译一下

**Comment by wenfxl** [comment]
ok linux 可以正常使用 感谢
