### ISSUE TITLE
The command contains the following subfunctions: info, quit

### ISSUE THREAD

**Issue by Dr1mH4X** [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin#11]
1：!yun gedanid 2026031766
<13:52:55> "TS3AudioBot": 
cpu: 0% 
memory: 112MB 
startime: 7/27/2023 5:460 AM
直接给我返回info的信息或者
"TS3AudioBot": The command contains the following subfunctions: info, quit

**Comment by ZHANGTIANYAO1** [comment]
请提供日志，日志在logs文件夹下

**Comment by ZHANGTIANYAO1** [comment]
请先加载插件再使用插件命令
