### ISSUE TITLE
 部署问题 Error: Plugin error: UnknownError

### ISSUE THREAD

**Issue by KoishiID** [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin#13]
[ts3audiobot_2023-08-09_07_08_38.log](https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/files/12296772/ts3audiobot_2023-08-09_07_08_38.log)

**Comment by ZHANGTIANYAO1** [comment]
官方的有点问题，请使用我之前版本构件的linux版的文件
