### ISSUE TITLE
!yun play 歌曲名报错Error: Unknown request error.

### ISSUE THREAD

**Issue by Kun99SAMA** [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin#15]
[ts3audiobot_2023-08-12_12_38_23.log](https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/files/12326590/ts3audiobot_2023-08-12_12_38_23.log)

**Comment by Kun99SAMA** [comment]
上面的log不知道为什么没有报错信息，放个新的作为补充
[ts3audiobot_2023-08-12_12_53_14.log](https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/files/12326607/ts3audiobot_2023-08-12_12_53_14.log)

**Comment by ZHANGTIANYAO1** [comment]
网易云API没有正确部署，请检查，使用默认端口
________________________________
发件人: Kun99SAMA ***@***.***>
发送时间: 2023年8月12日 12:56
收件人: ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin] !yun play 歌曲名报错Error: Unknown request error. (Issue #15)

        - External Email -



上面的log不知道为什么没有报错信息，放个新的作为补充
ts3audiobot_2023-08-12_12_53_14.log<https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/files/12326607/ts3audiobot_2023-08-12_12_53_14.log>

―

**Comment by Kun99SAMA** [comment]
好的谢谢，已经解决了，服务器没有开放30033端口无法实现文件传输，导致歌曲封面和登录二维码无法加载报错，开放30033端口后问题解决
