### ISSUE TITLE
没有执行插件成功

### ISSUE THREAD

**Issue by sanorintea** [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin#2]
我先建了个Plugins文件夹在根目录。
然后往文件夹里放了yunplugin.cs。
然后启动exe。
bot进入频道后，我输入!plugin list，有一堆黄色的warning
——————————————————————————
2023-03-23 09:13:01.8768| INFO|0|Bot.OnMessageReceived User Admin requested: !plugin list
2023-03-23 09:13:05.7956| WARN|0|Plugin.PrepareSource Plugin "yunplugin.cs" [0] compiler notifications:
Error L7/C18: The type or namespace name 'Json' does not exist in the namespace 'System.Text' (are you missing an assembly reference?)
Error L34/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Hidden L3108/C52: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.
Error L3108/C62: The type or namespace name 'EventArgs' could not be found (are you missing a using directive or an assembly reference?)
Error L3108/C17: The type or namespace name 'Task' could not be found (are you missing a using directive or an assembly reference?)
Error L1487/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Error L78/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Error L1527/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Error L1535/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Error L158/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Hidden L1619/C17: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.
Hidden L1615/C17: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.
Error L178/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Error L210/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Error L394/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Error L414/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Error L418/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Error L438/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Error L538/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Error L542/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Error L1941/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Error L1945/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Error L622/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Hidden L650/C17: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.
Hidden L662/C17: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.
Hidden L666/C17: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.
Hidden L670/C17: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.
Error L2025/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Hidden L694/C17: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.
Hidden L594/C17: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.
Hidden L598/C17: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.
Hidden L602/C17: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.
Hidden L614/C17: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.
Hidden L646/C17: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.
Error L2249/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Error L846/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Error L2289/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Error L854/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Error L2301/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Error L858/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Error L2313/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Error L935/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Error L983/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Error L2509/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Error L1031/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Error L2533/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Error L1111/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Error L1115/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Error L2582/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Error L1131/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Error L2586/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Error L2606/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Error L2734/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Error L1311/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Error L2738/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Error L1335/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Error L2818/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Error L1403/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Error L3042/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Error L3050/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Error L3054/C11: The type or namespace name 'List<>' could not be found (are you missing a using directive or an assembly reference?)
Error L3131/C17: The type or namespace name 'Task<>' could not be found (are you missing a using directive or an assembly reference?)
Error L3158/C46: The type or namespace name 'Queue<>' could not be found (are you missing a using directive or an assembly reference?)
Error L3158/C24: The type or namespace name 'Task' could not be found (are you missing a using directive or an assembly reference?)
Error L3180/C24: The type or namespace name 'Task<>' could not be found (are you missing a using directive or an assembly reference?)
Error L3209/C24: The type or namespace name 'Task<>' could not be found (are you missing a using directive or an assembly reference?)
Error L3238/C24: The type or namespace name 'Task<>' could not be found (are you missing a using directive or an assembly reference?)
Error L3260/C24: The type or namespace name 'Task<>' could not be found (are you missing a using directive or an assembly reference?)
Error L3282/C17: The type or namespace name 'Task<>' could not be found (are you missing a using directive or an assembly reference?)
Error L3314/C17: The type or namespace name 'Task<>' could not be found (are you missing a using directive or an assembly reference?)
Error L3402/C24: The type or namespace name 'Task<>' could not be found (are you missing a using directive or an assembly reference?)
Error L3075/C18: The type or namespace name 'Queue<>' could not be found (are you missing a using directive or an assembly reference?)
Error L3076/C4: The type or namespace name 'SemaphoreSlim' could not be found (are you missing a using directive or an assembly reference?)
Error L3075/C47: The type or namespace name 'Queue<>' could not be found (are you missing a using directive or an assembly reference?)
Error L3076/C33: The type or namespace name 'SemaphoreSlim' could not be found (are you missing a using directive or an assembly reference?)
Error L3086/C8: The name 'Console' does not exist in the current context
Warning L3079/C8: Assignment made to same variable; did you mean to assign something else?
Warning L3080/C8: Assignment made to same variable; did you mean to assign something else?
Warning L3081/C8: Assignment made to same variable; did you mean to assign something else?
Warning L3082/C8: Assignment made to same variable; did you mean to assign something else?
Warning L3083/C8: Assignment made to same variable; did you mean to assign something else?
Warning L3084/C8: Assignment made to same variable; did you mean to assign something else?
Warning L3085/C8: Assignment made to same variable; did you mean to assign something else?
Hidden L3077/C22: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
Error L3117/C16: An object of a type convertible to 'Task' is required
Error L3120/C12: The name 'Console' does not exist in the current context
Error L3121/C12: The name 'Console' does not exist in the current context
Error L3108/C22: 'YunPlgun.AudioService_Playstoped(object?, EventArgs)': not all code paths return a value
Error L3135/C12: No overload for 'AudioService_Playstoped' matches delegate 'AsyncEventHandler'
Error L3136/C12: The name 'Console' does not exist in the current context
Error L3145/C34: The name 'JsonSerializer' does not exist in the current context
Error L3153/C8: The name 'Console' does not exist in the current context
Error L3163/C23: The name 'JsonSerializer' does not exist in the current context
Error L3167/C12: The name 'Console' does not exist in the current context
Hidden L3158/C29: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
Error L3158/C29: 'YunPlgun.genList(long, Queue<string>, Ts3Client)': not all code paths return a value
Hidden L3184/C21: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.
Error L3184/C39: The name 'JsonSerializer' does not exist in the current context
Error L3187/C8: The name 'Console' does not exist in the current context
Error L3191/C34: The name 'JsonSerializer' does not exist in the current context
Error L3196/C8: The name 'Console' does not exist in the current context
Hidden L3199/C12: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.
Hidden L3200/C12: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.
Hidden L3201/C12: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.
Hidden L3213/C21: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.
Error L3213/C39: The name 'JsonSerializer' does not exist in the current context
Error L3216/C8: The name 'Console' does not exist in the current context
Error L3220/C34: The name 'JsonSerializer' does not exist in the current context
Error L3225/C8: The name 'Console' does not exist in the current context
Hidden L3228/C12: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.
Hidden L3229/C12: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.
Hidden L3230/C12: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.
Error L3243/C34: The name 'JsonSerializer' does not exist in the current context
Error L3248/C8: The name 'Console' does not exist in the current context
Hidden L3251/C12: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.
Hidden L3252/C12: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.
Error L3263/C8: The name 'Console' does not exist in the current context
Error L3266/C34: The name 'JsonSerializer' does not exist in the current context
Hidden L3273/C12: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.
Hidden L3274/C12: Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call.
Error L3286/C34: The name 'JsonSerializer' does not exist in the current context
Error L3290/C12: No overload for 'AudioService_Playstoped' matches delegate 'AsyncEventHandler'
Error L3291/C12: The name 'Console' does not exist in the current context
Error L3300/C34: The name 'JsonSerializer' does not exist in the current context
Error L3308/C8: The name 'Console' does not exist in the current context
Error L3324/C12: The name 'Console' does not exist in the current context
Error L3325/C12: The name 'Console' does not exist in the current context
Error L3351/C28: The name 'JsonSerializer' does not exist in the current context
Error L3370/C28: The name 'JsonSerializer' does not exist in the current context
Error L3385/C15: The type or namespace name 'StreamReader' could not be found (are you missing a using directive or an assembly reference?)
Error L3385/C41: The type or namespace name 'StreamReader' could not be found (are you missing a using directive or an assembly reference?)
Error L3406/C8: The name 'Console' does not exist in the current context
Error L3407/C28: The name 'JsonSerializer' does not exist in the current context
Error L3411/C28: The name 'JsonSerializer' does not exist in the current context
Error L3415/C8: The name 'Console' does not exist in the current context
Error L3417/C23: The name 'Convert' does not exist in the current context
Error L3418/C8: The type or namespace name 'Stream' could not be found (are you missing a using directive or an assembly reference?)
Error L3418/C28: The type or namespace name 'MemoryStream' could not be found (are you missing a using directive or an assembly reference?)
Error L3428/C12: The name 'Console' does not exist in the current context
Error L3429/C30: The name 'JsonSerializer' does not exist in the current context
Error L3435/C12: The name 'Thread' does not exist in the current context
Error L3456/C8: The type or namespace name 'TimeSpan' could not be found (are you missing a using directive or an assembly reference?)
Error L3456/C22: The name 'DateTime' does not exist in the current context
Error L3456/C41: The type or namespace name 'DateTime' could not be found (are you missing a using directive or an assembly reference?)
Error L3457/C15: The name 'Convert' does not exist in the current context

**Comment by ZHANGTIANYAO1** [comment]
你使用的是官方构建的ts3audiobot吗

**Comment by sanorintea** [comment]
我在3000 端口运行了网易云API，然后又打开试了下，好像也不行

**Comment by ZHANGTIANYAO1** [comment]
你用我打包的那个版本，不要用官方的构建，那个编译环境有问题

**Comment by sanorintea** [comment]
> 你用我打包的那个版本，不要用官方的构建，那个编译环境有问题

你构建的版本应该在哪下载呢- -

**Comment by ZHANGTIANYAO1** [comment]
如果是win版本看最新发布的1.2.0，如果是Linux看1.1.0，然后把插件自己更新一下

**Comment by sanorintea** [comment]
> 如果是win版本看最新发布的1.2.0，如果是Linux看1.1.0，然后把插件自己更新一下

是win版本，但是我没有找到你打包的ts3audiobot版本应该在哪里下载？

**Comment by ZHANGTIANYAO1** [comment]
TS3bot-win.zip

**Comment by sanorintea** [comment]
windows环境用了你的构建就可以正常使用，感谢
