### ISSUE TITLE
本人小白too，使用centos7，求centos的插件安装教程，通过安装之后，报错Error: Requested command is ambiguous between: info, quit

### ISSUE THREAD

**Issue by zhuangzibo123** [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin#21]
<img width="537" alt="image" src="https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/assets/83704559/56af4ae2-88d2-414b-8455-78f34dd2cd89">
<img width="545" alt="image" src="https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/assets/83704559/c0f8d3a1-ab23-4046-b8fe-0deff1dd6c60">
添加了这个文件，不知如何运行，主程序需要进行修改吗？

**Comment by zhuangzibo123** [comment]
环境什么的都安排好了，只差插件

**Comment by zhuangzibo123** [comment]
<img width="813" alt="image" src="https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/assets/83704559/5597c344-3f48-4fa3-a5d3-b9a4447f8e04">
<img width="427" alt="image" src="https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/assets/83704559/11bf6aca-6a6e-4348-b8c4-96504d2aaa9f">

**Comment by zhuangzibo123** [comment]
经过我的不断尝试，最后一个问题，不知道咋解决：
Unknown request error
<img width="762" alt="image" src="https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/assets/83704559/c325289f-9b39-4827-bb09-d6b863b0d792">
<img width="363" alt="image" src="https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/assets/83704559/82b16b0a-93bd-4f74-bc0a-7583bc645293">

**Comment by ZHANGTIANYAO1** [comment]
没看懂最后这个有啥问题，显示的是正常的日志信息，没有报错

**Comment by zhuangzibo123** [comment]
就是单单这个，需要如何解决？
<img width="344" alt="image" src="https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/assets/83704559/c262a28c-0cdf-49af-acd7-26d9746ce693">

**Comment by ZHANGTIANYAO1** [comment]
请上传完整的日志文件，日志在bot文件夹的logs里面

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by FiveHair** [comment]
如果没有什么特殊要求的话可以使用Docker版的TS3AudioBot，直接把插件扔到映射出来的目录里就ok了。

**Comment by zhuangzibo123** [comment]
[ts3audiobot_2023-08-20_18_16_43.log](https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/files/12394456/ts3audiobot_2023-08-20_18_16_43.log)
大佬帮忙看下日志谢谢

**Comment by FiveHair** [comment]
> [ts3audiobot_2023-08-20_18_16_43.log](https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/files/12394456/ts3audiobot_2023-08-20_18_16_43.log) 大佬帮忙看下日志谢谢

你的NeteaseCloudMusicApi部署好了？

**Comment by zhuangzibo123** [comment]
是的，部署好了，https://wyy.zhuangjiajun.cn/，同一个服务器，这个部署好没做修改

**Comment by FiveHair** [comment]
> 是的，部署好了，[https://wyy.zhuangjiajun.cn/，同一个服务器，这个部署好没做修改](https://wyy.zhuangjiajun.cn/%EF%BC%8C%E5%90%8C%E4%B8%80%E4%B8%AA%E6%9C%8D%E5%8A%A1%E5%99%A8%EF%BC%8C%E8%BF%99%E4%B8%AA%E9%83%A8%E7%BD%B2%E5%A5%BD%E6%B2%A1%E5%81%9A%E4%BF%AE%E6%94%B9)

[releases有打包好的AudioBot](https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/releases/tag/1.1.0)你可以试一下

**Comment by zhuangzibo123** [comment]
是的，我使用中的是这个打包好的版本😂，还是摸不清楚是哪里出现的问题

**Comment by FiveHair** [comment]
> 是的，我使用中的是这个打包好的版本😂，还是摸不清楚是哪里出现的问题

有时间的话试试docker版本的bot，如果没有问题的话就是你环境的问题了

**Comment by zhuangzibo123** [comment]
请问您说的docker版本的bot是官方的那个吗，然后按照常规的三个插件文件加到bot中，是这样么

**Comment by FiveHair** [comment]
> 请问您说的docker版本的bot是官方的那个吗，然后按照常规的三个插件文件加到bot中，是这样么

对的，其实只需要dll就可以，另外两个文件无所谓的。
