### ISSUE TITLE
刚接触github，不怎么会用。 歌曲解锁我放在我的分支里了

### ISSUE THREAD

**Issue by FiveHair** [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin#25]
https://github.com/FiveHair/TS3AudioBot-NetEaseCloudmusic-plugin

**Comment by FiveHair** [comment]
可以做个参考

**Comment by ZHANGTIANYAO1** [comment]
看到了，感谢你的帮助，之后更新会加进去的。目前正在进行的是播放模式的大改，估计一些东西要重新写，需要一些时间
