### ISSUE TITLE
配合最新版本的NeteaseMusic API好像没有实现功能

### ISSUE THREAD

**Issue by JackesRrmhX** [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin#3]
我算个TS小白，我试了安装您说的插件后，对应权限也已经提供了，但输入任何关于!yun的命令都没有正确的输出
![image](https://user-images.githubusercontent.com/48159667/230780396-9f78aac8-eebf-43d3-b3ee-1b9cdbc94cb8.png)

**Comment by JackesRrmhX** [comment]
![image](https://user-images.githubusercontent.com/48159667/230780438-65c5e0e3-e80a-4eb6-99f7-f81d772d6c34.png)
这个也没有对应的提示，如果您可以方便出一个教程等就最好了，感激不尽

**Comment by ZHANGTIANYAO1** [comment]
你应该是没有加载上插件

**Comment by ZHANGTIANYAO1** [comment]
我看看这周有没有空，如果没有就下周出一个教程

**Comment by JackesRrmhX** [comment]
是的，我试了下，好像是因为没有加载插件，我这个是公有云上的，还需要安装vs2015的运行库 要不然就会暴露C# Exception has been thrown by the target of an invocation(调用的目标已抛出异常) 最近我也在研究怎么弄API对接歌词，机器人的名字修改为歌词这样的方式 多多交流

**Comment by JackesRrmhX** [comment]
感谢作者大佬，这个我就先关闭了

**Comment by FFatTiger** [comment]
礼貌询问，咋解决的？我安装了vs2015跟你提示一样的错误，Exception has been thrown by the target of an invocation(调用的目标已抛出异常)
![image](https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/assets/55613704/c1c42375-d105-4312-b7d8-43ee20d5ed25)
![image](https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/assets/55613704/9344b69b-72fd-4c1d-9f90-56c3291f247d)
