### ISSUE TITLE
启动插件时发生错误

### ISSUE THREAD

**Issue by muyan6** [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin#31]
ERROR|0| Plugin 'YunPlgun (BotPlugin)' failed to load: The type initializer for '<Module>' threw an exception..
似乎是由于我是linux系统，我是第一次使用，用的是YunPlgun-unm那个插件

**Comment by FiveHair** [comment]
> ERROR|0| Plugin 'YunPlgun (BotPlugin)' failed to load: The type initializer for '' threw an exception.. 似乎是由于我是linux系统，我是第一次使用，用的是YunPlgun-unm那个插件

能否发下完整的日志

**Comment by muyan6** [comment]
> > 错误|0|插件“YunPlgun （BotPlugin）”加载失败：“”的类型初始值设定项引发异常。似乎是由于我是linux系统，我是第一次使用，用的是YunPlgun-unm那个插件
> 
> 能否发下完整的日志

原因好像是我没有用之前的linux整合包，现在可以打开了

**Comment by muyan6** [comment]
现在出现另一个问题，网页无法打开
12:58:48.2429| INFO|Core| [============ TS3AudioBot started =============]
12:58:48.2785| INFO|Core| [ Date: Saturday, 09 September 2023 12:58:48
12:58:48.3259| INFO|Core| [ Version: <?>/<?>/<?>
12:58:48.3262| INFO|Core| [ Build: <?>
12:58:48.3262| INFO|Core| [ Platform: CentOS Linux 7 (Core) (64bit)
12:58:48.3262| INFO|Core| [ Runtime: .NET Framework 3.1.32 ServerGC:False GC:SustainedLowLatency
12:58:48.3262| INFO|Core| [ Opus: libopus 1.0.2 (x64)
12:58:48.3262| INFO|Core| [==============================================]
12:58:48.8551|ERROR|Core| Can't find a WebInterface path to host. Try specifying the path to host in the config
12:58:48.8561| INFO|Core| Starting Webserver on port 58913
12:58:49.0101| INFO|Core| WebServer has closed
12:58:49.0143|ERROR|Core| The webserver could not be started

**Comment by muyan6** [comment]
现在有了新的问题，机器人的网页无法启动而且无法播放音乐
13:12:22.9889| INFO|Core| [============ TS3AudioBot started =============]
13:12:23.0224| INFO|Core| [ Date: Saturday, 09 September 2023 13:12:23
13:12:23.0684| INFO|Core| [ Version: <?>/<?>/<?>
13:12:23.0684| INFO|Core| [ Build: <?>
13:12:23.0684| INFO|Core| [ Platform: CentOS Linux 7 (Core) (64bit)
13:12:23.0684| INFO|Core| [ Runtime: .NET Framework 3.1.32 ServerGC:False GC:SustainedLowLatency
13:12:23.0698| INFO|Core| [ Opus: libopus 1.0.2 (x64)
13:12:23.0698| INFO|Core| [==============================================]
13:12:23.5210| INFO|Core| Starting Webserver on port 58913
13:12:23.6717| INFO|Core| WebServer has closed
13:12:23.6763|ERROR|Core| The webserver could not be started
而且无法播放音乐
13:13:24.2283|ERROR|0| Unexpected command error: The SSL connection could not be established, see inner exception. The remote certificate is invalid according to the validation procedure.

**Comment by FiveHair** [comment]
> 现在有了新的问题，机器人的网页无法启动而且无法播放音乐 13:12:22.9889| INFO|Core| [============ TS3AudioBot started =============] 13:12:23.0224| INFO|Core| [ Date: Saturday, 09 September 2023 13:12:23 13:12:23.0684| INFO|Core| [ Version: // 13:12:23.0684| INFO|Core| [ Build: 13:12:23.0684| INFO|Core| [ Platform: CentOS Linux 7 (Core) (64bit) 13:12:23.0684| INFO|Core| [ Runtime: .NET Framework 3.1.32 ServerGC:False GC:SustainedLowLatency 13:12:23.0698| INFO|Core| [ Opus: libopus 1.0.2 (x64) 13:12:23.0698| INFO|Core| [==============================================] 13:12:23.5210| INFO|Core| Starting Webserver on port 58913 13:12:23.6717| INFO|Core| WebServer has closed 13:12:23.6763|ERROR|Core| The webserver could not be started 而且无法播放音乐 13:13:24.2283|ERROR|0| Unexpected command error: The SSL connection could not be established, see inner exception. The remote certificate is invalid according to the validation procedure.

推荐使用docker版的ts，奇怪的问题会少一些。
播放音乐看报错是网络问题？你的网易云api正常吗？

**Comment by muyan6** [comment]
> > 现在有了新的问题，机器人的网页无法启动而且无法播放音乐 13:12:22.9889|信息|核心|[============ TS3音频机器人已启动 ==============] 13：12：23.0224|信息|核心|[ 日期：09 年 2023 月 13 日星期六 12：23：13 12：23：0684.13|信息|核心|[ 版本： // 12：23：0684.13|信息|核心|[ 内部版本： 12：23：0684.7|信息|核心|[ 平台： CentOS Linux 64 （核心） （13位） 12：23：0684.3|信息|核心|[ 运行时： .NET Framework 1.32.13 ServerGC：False GC：SustainedLowLatency 12：23：0698.1|信息|核心|[ 作品： libopus 0.2.64 （x13） 12：23：0698.13|信息|核心|[===========================================================================================================================================================================================信息|核心|在端口 12 上启动 Web 服务器 23：5210：58913.13|信息|核心|Web服务器已关闭 12：23：6717.13|错误|核心|无法启动 Web 服务器 而且无法播放音乐 12：23：6763.13|错误|13|意外命令错误：无法建立 SSL 连接，请参阅内部异常。根据验证过程，远程证书无效。
> 
> 推荐使用docker版的ts，奇怪的问题会少一些。 播放音乐看报错是网络问题？你的网易云api正常吗？

用的是插件自带的，奇奇怪怪的

**Comment by ZHANGTIANYAO1** [comment]
> > > 现在有了新的问题，机器人的网页无法启动而且无法播放音乐 13:12:22.9889|信息|核心|[============ TS3音频机器人已启动 ==============] 13：12：23.0224|信息|核心|[ 日期：09 年 2023 月 13 日星期六 12：23：13 12：23：0684.13|信息|核心|[ 版本： // 12：23：0684.13|信息|核心|[ 内部版本： 12：23：0684.7|信息|核心|[ 平台： CentOS Linux 64 （核心） （13位） 12：23：0684.3|信息|核心|[ 运行时： .NET Framework 1.32.13 ServerGC：False GC：SustainedLowLatency 12：23：0698.1|信息|核心|[ 作品： libopus 0.2.64 （x13） 12：23：0698.13|信息|核心|[===========================================================================================================================================================================================信息|核心|在端口 12 上启动 Web 服务器 23：5210：58913.13|信息|核心|Web服务器已关闭 12：23：6717.13|错误|核心|无法启动 Web 服务器 而且无法播放音乐 12：23：6763.13|错误|13|意外命令错误：无法建立 SSL 连接，请参阅内部异常。根据验证过程，远程证书无效。
> > 
> > 
> > 推荐使用docker版的ts，奇怪的问题会少一些。 播放音乐看报错是网络问题？你的网易云api正常吗？
> 
> 用的是插件自带的，奇奇怪怪的

你防火墙开放了吗

**Comment by muyan6** [comment]
> > > > 现在有了新的问题，机器人的网页无法启动而且无法播放音乐 13:12:22.9889|信息|核心|[============ TS3音频机器人已启动 ==============] 13：12：23.0224|信息|核心|[ 日期：09 年 2023 月 13 日星期六 12：23：13 12：23：0684.13|信息|核心|[ 版本： // 12：23：0684.13|信息|核心|[ 内部版本： 12：23：0684.7|信息|核心|[ 平台： CentOS Linux 64 （核心） （13位） 12：23：0684.3|信息|核心|[ 运行时： .NET Framework 1.32.13 ServerGC：False GC：SustainedLowLatency 12：23：0698.1|信息|核心|[ 作品： libopus 0.2.64 （x13） 12：23：0698.13|信息|核心|[===========================================================================================================================================================================================信息|核心|在端口 12 上启动 Web 服务器 23：5210：58913.13|信息|核心|Web服务器已关闭 12：23：6717.13|错误|核心|无法启动 Web 服务器 而且无法播放音乐 12：23：6763.13|错误|13|意外命令错误：无法建立 SSL 连接，请参阅内部异常。根据验证过程，远程证书无效。
> > > 
> > > 
> > > 推荐使用docker版的ts，奇怪的问题会少一些。 播放音乐看报错是网络问题？你的网易云api正常吗？
> > 
> > 
> > 用的是插件自带的，奇奇怪怪的
> 
> 你防火墙开放了吗

开放了的，之前用原版是能正常使用，不管了不管了，就上传几首喜欢的玩玩

**Comment by miachannel1** [comment]
我也遇到了相同的问题，用的1.1.0版本装的bot，插件也换成了最新的UNM版本，但是启动会报错
"TS3AudioBot": Error: Plugin error: UnknownError

22:26:21.7500| INFO|Core| [============ TS3AudioBot started =============]
22:26:21.8046| INFO|Core| [ Date: Monday, 18 September 2023 22:26:21
22:26:21.9003| INFO|Core| [ Version: 0.12.0/master/768c1867
22:26:21.9003| INFO|Core| [ Build: Release
22:26:21.9003| INFO|Core| [ Platform: CentOS Linux 7 (Core) (64bit)
22:26:21.9010| INFO|Core| [ Runtime: .NET Framework 3.1.13 ServerGC:False GC:SustainedLowLatency
22:26:21.9010| INFO|Core| [ Opus: libopus 1.0.2 (x64)
22:26:21.9010| INFO|Core| [==============================================]
22:26:22.3950| INFO|Core| Starting Webserver on port 58913
22:26:22.6078| INFO|Core| Bot "default" connecting to "*****:9987"
22:26:23.0156| INFO|Core| Client connected.
22:26:27.8858| INFO|0| User 二十 requested: !plugin load 0
22:26:27.9875|ERROR|0| Plugin 'YunPlgun (BotPlugin)' failed to load: The type initializer for '<Module>' threw an exception..

**Comment by FiveHair** [comment]
> 我也遇到了相同的问题，用的1.1.0版本装的bot，插件也换成了最新的UNM版本，但是启动会报错 "TS3AudioBot": Error: Plugin error: UnknownError
> 
> 22:26:21.7500| INFO|Core| [============ TS3AudioBot started =============] 22:26:21.8046| INFO|Core| [ Date: Monday, 18 September 2023 22:26:21 22:26:21.9003| INFO|Core| [ Version: 0.12.0/master/768c1867 22:26:21.9003| INFO|Core| [ Build: Release 22:26:21.9003| INFO|Core| [ Platform: CentOS Linux 7 (Core) (64bit) 22:26:21.9010| INFO|Core| [ Runtime: .NET Framework 3.1.13 ServerGC:False GC:SustainedLowLatency 22:26:21.9010| INFO|Core| [ Opus: libopus 1.0.2 (x64) 22:26:21.9010| INFO|Core| [==============================================] 22:26:22.3950| INFO|Core| Starting Webserver on port 58913 22:26:22.6078| INFO|Core| Bot "default" connecting to "*****:9987" 22:26:23.0156| INFO|Core| Client connected. 22:26:27.8858| INFO|0| User 二十 requested: !plugin load 0 22:26:27.9875|ERROR|0| Plugin 'YunPlgun (BotPlugin)' failed to load: The type initializer for '' threw an exception..

换docker版或者最新版的TS3AudioBot试一下呢？
我是基于最新版docker测试的，现在正在搭建linux版TS3AudioBot测试

**Comment by muyan6** [comment]
我现在可以正常播放音乐，但是网页端还是无法启用
13:11:38.6091| INFO|Core| [============ TS3AudioBot started =============]
13:11:38.6462| INFO|Core| [ Date: Tuesday, 19 September 2023 13:11:38
13:11:38.6852| INFO|Core| [ Version: <?>/<?>/<?>
13:11:38.6855| INFO|Core| [ Build: <?>
13:11:38.6855| INFO|Core| [ Platform: CentOS Linux 7 (Core) (64bit)
13:11:38.6855| INFO|Core| [ Runtime: .NET Framework 3.1.32 ServerGC:False GC:SustainedLowLatency
13:11:38.6855| INFO|Core| [ Opus: libopus 1.0.2 (x64)
13:11:38.6867| INFO|Core| [==============================================]
13:11:39.0472|ERROR|Core| Can't find a WebInterface path to host. Try specifying the path to host in the config
13:11:39.0483| INFO|Core| Starting Webserver on port 58913
13:11:39.1732| INFO|Core| WebServer has closed
13:11:39.1775|ERROR|Core| The webserver could not be started
13:11:39.2410| INFO|Core| Bot "default" connecting to "xxx.xx.xx.xx"
13:11:39.6170| INFO|Core| Client connected.
13:13:01.9602| INFO|0| User 春风肩上停 requested: !plugins load 0
Yun Plugin loaded
3

https://autumnfish.cn
13:13:14.5687| INFO|0| User 春风肩上停 requested: !yun play 老人与海
95475老人与海
http://m801.music.126.net/20230919133815/d78fb7577bbf1240838a0de4a723ed2c/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/10744280492/be59/c391/aa17/8bcda28257e923b6f94a6da7c10b05c3.mp3
13:13:15.9773|ERROR|| Unobserved Task error!
13:13:15.9791|ERROR|| Unobserved Task error!

**Comment by ZHANGTIANYAO1** [comment]
> 我现在可以正常播放音乐，但是网页端还是无法启用 13:11:38.6091| 信息|核心| [============ TS3AudioBot 已启动 =============] 13:11:38.6462| 信息|核心| [ 日期： 2023 年 9 月 19 日星期二 13:11:38 13:11:38.6852| 信息|核心| [版本： // 13:11:38.6855| 信息|核心| [构建： 13:11:38.6855| 信息|核心| [平台：CentOS Linux 7（核心）（64位） 13:11:38.6855| 信息|核心| [运行时：.NET Framework 3.1.32 ServerGC：False GC：持续低延迟 13：11：38.6855| 信息|核心| [作品：libopus 1.0.2 (x64) 13:11:38.6867| 信息|核心| [================================================] 13： 11:39.0472|错误|核心| 找不到主机的 WebInterface 路径。尝试在配置中指定主机路径 13:11:39.0483| 信息|核心| 在端口 58913 上启动 Web 服务器 13:11:39.1732| 信息|核心| Web 服务器已关闭 13:11:39.1775|错误|核心| 无法启动网络服务器 13:11:39.2410| 信息|核心| 机器人“默认”连接到“xxx.xx.xx.xx” 13:11:39.6170| 信息|核心| 客户端已连接。 13:13:01.9602| 信息|0| 用户春风肩上停请求： !plugins load 0 Yun 插件已加载 3
> 
> https://autumnfish.cn 13:13:14.5687| 信息|0| 用户春风肩上停请求：!yun play 老人与海 95475老人与海 [http://m801.music.126.net/20230919133815/d78fb7577bbf1240838a0de4a723ed2c/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/10744280492/be](http://m801.music.126.net/20230919133815/d78fb7577bbf1240838a0de4a723ed2c/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/10744280492/be59/c391/aa17/8bcda28257e923b6f94a6da7c10b05c3.mp3) 59/c391/aa17/8bcda28257e923b6f94a6da7c10b05c3.mp3 13:13:15.9773|错误|| 未观察到的任务错误！ 13:13:15.9791|错误|| 未观察到的任务错误！

网页端与本插件无关，本插件现在将来都不会支持网页端。如果遇到TS3AudioBot的网页端问题，请去该项目找作者反馈

**Comment by Xoc001** [comment]
我的linux 用构建好的版本导入插件以后load 报错这个是什么问题
 failed to load: Could not find a part of the path '/root/linux-x64/data/plugins/YunSettings.ini'..

**Comment by FiveHair** [comment]
YunSettings.ini也需要和插件放在一起




---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月22日(周五) 中午11:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin] 启动插件时发生错误 (Issue #31)




 
我的linux 用构建好的版本导入插件以后load 报错这个是什么问题
 failed to load: Could not find a part of the path '/root/linux-x64/data/plugins/YunSettings.ini'..

**Comment by Xoc001** [comment]
![image](https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/assets/57620373/e7124e6b-928c-4351-af16-4ccf037d871b)
在plugins中确实引入了两个文件，但load时报错

**Comment by muyan6** [comment]
这个问题我也遇到了，在机器人根目录里建一个/data/plugins文件夹然后把插件和插件配置复制进去就行了

**Comment by FiveHair** [comment]
@muyan6 @Xoc001 请试试新版[2.0.3.1](https://github.com/FiveHair/TS3AudioBot-NetEaseCloudmusic-plugin-UNM/releases/tag/2.0.3.1)
直接把ini和dll放在plugins就行

**Comment by gpf1202** [comment]
> 请试试新版[2.0.3.1](https://github.com/FiveHair/TS3AudioBot-NetEaseCloudmusic-plugin-UNM/releases/tag/2.0.3.1) 直接把ini和dll放在plugins就行

 我也遇到这个问题了 2.0.3.1还不行
还是说我的plugins文件夹位置不对

**Comment by gpf1202** [comment]
![image](https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/assets/56463144/187b545e-f928-468b-a41a-5350a0902226)

**Comment by gpf1202** [comment]
![image](https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/assets/56463144/24ff76bb-f61c-470a-8fdc-004381daf58a)

**Comment by FiveHair** [comment]
需要使用ZHANGTIANYAO1的linux整合包



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月26日(周二) 凌晨1:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin] 启动插件时发生错误 (Issue #31)




  
请试试新版2.0.3.1 直接把ini和dll放在plugins就行
  
我也遇到这个问题了 2.0.3.1还不行
 还是说我的plugins文件夹位置不对

**Comment by gpf1202** [comment]
> 需要使用ZHANGTIANYAO1的linux整合包
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年9月26日(周二) 凌晨1:29 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin] 启动插件时发生错误 (Issue #31) 请试试新版2.0.3.1 直接把ini和dll放在plugins就行 我也遇到这个问题了 2.0.3.1还不行 还是说我的plugins文件夹位置不对 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

具体的使用方法您可以发一下吗  感谢

**Comment by gpf1202** [comment]
> 需要使用ZHANGTIANYAO1的linux整合包
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年9月26日(周二) 凌晨1:29 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin] 启动插件时发生错误 (Issue #31) 请试试新版2.0.3.1 直接把ini和dll放在plugins就行 我也遇到这个问题了 2.0.3.1还不行 还是说我的plugins文件夹位置不对 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

![image](https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/assets/56463144/8e9f99d5-93b4-4fd7-9d1a-f47907da3d86)

**Comment by ZHANGTIANYAO1** [comment]
> > 需要使用ZHANGTIANYAO1的linux整合包
> > […](#)
> > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2023年9月26日(周二) 凌晨1:29 收件人: _**@**_.**_>; 抄送: _**@**_._**_**@**_.**_>; 主题: Re: [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin] 启动插件时发生错误 (Issue #31) 请试试新版2.0.3.1 直接把ini和dll放在plugins就行 我也遇到这个问题了 2.0.3.1还不行 还是说我的plugins文件夹位置不对 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> ![image](https://user-images.githubusercontent.com/56463144/270564897-8e9f99d5-93b4-4fd7-9d1a-f47907da3d86.png)

外部的网易云API暂时用不了，请自行部署

**Comment by gpf1202** [comment]
> > > 需要使用ZHANGTIANYAO1的linux整合包
> > > […](#)
> > > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2023年9月26日(周二) 凌晨1:29 收件人: _**@**_.**_>; 抄送: _**@**_._**_**@**_.**_>; 主题: Re: [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin] 启动插件时发生错误 (Issue #31) 请试试新版2.0.3.1 直接把ini和dll放在plugins就行 我也遇到这个问题了 2.0.3.1还不行 还是说我的plugins文件夹位置不对 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/56463144/270564897-8e9f99d5-93b4-4fd7-9d1a-f47907da3d86.png)
> 
> 外部的网易云API暂时用不了，请自行部署

好的
