### ISSUE TITLE
启动插件发生错误

### ISSUE THREAD

**Issue by Heroleaves** [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin#32]
15:22:26.5265|ERROR|0| Plugin 'YunPlgun (BotPlugin)' failed to load: The type initializer for '<Module>' threw an exception..
这个是log日志
插件是最新
![image](https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/assets/92717245/dac39cf3-bcd9-4e82-b87f-e64a1a60745a)

![image](https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/assets/92717245/190d8ea5-47b3-47de-9463-adf455bc297d)

**Comment by Heroleaves** [comment]
使用docker版就没问题，奇怪了

**Comment by ZHANGTIANYAO1** [comment]
emmm估计是环境问题，docker还是NB啊

**Comment by ZHANGTIANYAO1** [comment]
反正我现在也是能用docker就用docker
