### ISSUE TITLE
歌单创建者的id过长错误

### ISSUE THREAD

**Issue by BoomSun** [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin#34]
![3b8d70b137be94e2b23496de7366377d](https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/assets/82922619/bd62db43-ea64-4ef9-9384-999681e0b838)
一些新歌单ID太长了就会触发错误

**Comment by BoomSun** [comment]
哥们可以叫chatGPT给你修了得了 事半功倍

**Comment by ZHANGTIANYAO1** [comment]
并不是歌单id太长报错，而是歌单创建者的id过长

**Comment by BoomSun** [comment]
这个错误触发一次之后有概率使之前可以正常播放的歌单id也报这个错误，有什么临时解决办法吗，重启机器人喝重载插件都没用

**Comment by FiveHair** [comment]
![image](https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/assets/16514929/d3099b24-c3aa-499f-8778-4e70c7376c47)
我这里测试这个歌单可以播放，没有报错
