### ISSUE TITLE
Bot插件后台显示名称错误

### ISSUE THREAD

**Issue by ZombieAki** [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin#41]
![QQ截图20231102103826](https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/assets/19723289/6d445f39-505c-4b64-b22e-e906f88969a1)
YunPlgun很容易输入错误。

**Comment by ZombieAki** [comment]
![20231102104321](https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/assets/19723289/f5bf547c-fd98-47df-b001-ba707310c0f8)
配置文件如图。

**Comment by ZHANGTIANYAO1** [comment]
如果遇到问题请提交完整log文件，并描述问题情况

**Comment by ZHANGTIANYAO1** [comment]
请仔细确认是否使用最新版本的插件
