### ISSUE TITLE
ffmpeg已安装，TS3AudioBot.exe一打开就闪退

### ISSUE THREAD

**Issue by Zaki2380** [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin#47]
[logs.zip](https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/files/13608454/logs.zip)

操作系统Windows Server 2022 数据中心版 64位中文版

**Comment by ZHANGTIANYAO1** [comment]
看log是有一个lib没有加载可以google一下是不是sever版没有安装

**Comment by ZHANGTIANYAO1** [comment]
以及确认使用的是最新版本的打包文件
