### ISSUE TITLE
You cannot execute 'system info'. You are missing the 'cmd.system.info' right!

### ISSUE THREAD

**Issue by Yuzuki-Roa** [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin#48]
![QQ图片20231210185430](https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/assets/68953500/da142a3a-5579-4135-9860-5516b64e96b1)
![Uploading QQ图片20231210185611.png…]()
私聊登录后会提示这个

**Comment by ZHANGTIANYAO1** [comment]
能正常使用就不用管

**Comment by ZHANGTIANYAO1** [comment]
权限设置问题，下次更新应该会修复
