### ISSUE TITLE
二维码不显示，报错如图

### ISSUE THREAD

**Issue by hulinhao233** [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin#49]
<img width="980" alt="屏幕截图 2023-12-13 212648" src="https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/assets/42168924/d8067482-3c8c-44e1-8242-6adfb4541be6">

**Comment by ZHANGTIANYAO1** [comment]
没有给机器人设置头像的权限

**Comment by hulinhao233** [comment]
怎么给呢，我不是很懂怎么配置，ts3audiobot官方文档看不懂鸭

**Comment by ZHANGTIANYAO1** [comment]
teamspeak里面给

**Comment by ZHANGTIANYAO1** [comment]
查看给机器人的身份能不能设置头像

**Comment by hulinhao233** [comment]
我给的是最高级的权限，和我是一样的超级管理员权限，是可以设置头像的

**Comment by hulinhao233** [comment]
还是不太行，是不是我没有配置好的问题

**Comment by hulinhao233** [comment]
!api token这个指令都用不了，就很怪

**Comment by hulinhao233** [comment]
我好了，要先！api load
