### ISSUE TITLE
由于目标计算机积极拒绝。无法连接

### ISSUE THREAD

**Issue by MXbill** [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin#5]
TSAUbot已部署成功，网易云音乐API由服务器端部署成功，插件安装成功正常启动，但是在输入指令后会提示【由于目标计算机积极拒绝。无法连接】。请求指导，本人小白，是按照说明步骤部署的。

**Comment by MXbill** [comment]
17:50:21.9358| INFO|0| User mxX requested: !yun load
17:50:43.7097|ERROR|0| Unexpected command error: 由于目标计算机积极拒绝，无法连接。 由于目标计算机积极拒绝，无法连接。

**Comment by MXbill** [comment]
希望可以得到帮助，感谢

**Comment by sanorintea** [comment]
看起来是云服务器的安全策略组里某个端口没开？

**Comment by ZHANGTIANYAO1** [comment]
网易云api没有运行会导致此报错，需要先运行网易云api

**Comment by MXbill** [comment]
我是按照网易云API的腾讯云 serverless 部署方案进行部署的，测试可以收到网易云回传信息，这个方式会有影响么？还请具体指教一下。云服务器9987、58913端口都已打开。

**Comment by MXbill** [comment]
问题已解决，感谢
