### ISSUE TITLE
登录网易云账户扫码后显示：“An unexpected error occurred: The remote server returned an error: (502) Bad Gateway.”

### ISSUE THREAD

**Issue by Monseasdy** [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin#50]
如图
<img width="393" alt="屏幕截图 2023-12-17 145253" src="https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/assets/154041427/0b37dcb4-dd97-4b4f-bb6f-de568e12c026">
求大佬帮忙解决

**Comment by ZHANGTIANYAO1** [comment]
检查是否能正常访问网易云api，建议自行部署，目前默认的第三方api不可用

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Monseasdy ***@***.***>
Sent: Sunday, December 17, 2023 2:54:37 PM
To: ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin] 登录网易云账户扫码后显示：“An unexpected error occurred: The remote server returned an error: (502) Bad Gateway.” (Issue #50)

        - External Email -



如图
2023-12-17.145253.png (view on web)<https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/assets/154041427/0b37dcb4-dd97-4b4f-bb6f-de568e12c026>
求大佬帮忙解决

―

**Comment by Monseasdy** [comment]
感谢大佬，自行部署API后可以扫码登陆了
