### ISSUE TITLE
使用linux搭建的bot扫码登陆后没反应

### ISSUE THREAD

**Issue by 42wind** [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin#52]
扫码登陆后无任何提示，仍然无法播放VIP歌曲
<img width="773" alt="PixPin_2023-12-19_12-54-53" src="https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/assets/154301151/924ab89f-09dd-48ae-94bd-6914bbe61a6f">

**Comment by ZHANGTIANYAO1** [comment]
机器人缺少修改自己描述的权限

**Comment by 42wind** [comment]
使用的是之前提供的linux-x64版本 更新过了插件
