### ISSUE TITLE
使用作者提供的环境无法获取apikey

### ISSUE THREAD

**Issue by ljt1477059273** [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin#53]
如题所示问题已解决
无法播放歌单
<03:58:41> "MTong_huahua": !yun gedanid 5157014884
<03:58:42> "MusicBot": An unexpected error occurred: The remote server returned an error: (406) Not Acceptable.

**Comment by ljt1477059273** [comment]
看了以前的issues 正确载入插件后 貌似这个网易云api没用了
An unexpected error occurred: The SSL connection could not be established, see inner exception. Unable to read data from the transport connection: 远程主机强迫关闭了一个现有的连接。.

**Comment by ljt1477059273** [comment]
API也自行搭建了 但是又无法播放歌单
<03:58:41> "MTong_huahua": !yun gedanid 5157014884
<03:58:42> "MusicBot": An unexpected error occurred: The remote server returned an error: (406) Not Acceptable.

**Comment by sakurasep** [comment]
请更换网易云api,作者内置的api已经失效

**Comment by ljt1477059273** [comment]
您好作者 已经更换自己搭建的API  还是无法播放歌单  歌曲可以正常播放
播放模式也有问题 无法进行循环播放 也就是那个功能没用

**Comment by sakurasep** [comment]
请问你是使用什么环境搭建的?
目前来说,windows环境所有的功能可以正常使用
如果使用linux环境,最好使用docker,然后将plugins映射到容器中,虽然有一些显示bug,但是功能都是正常的
