### ISSUE TITLE
部署后58913端口无法访问？

### ISSUE THREAD

**Issue by Agniyz** [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin#54]
linux版本部署后58913端口无法访问，在ts中可以正常点歌

**Comment by ZHANGTIANYAO1** [comment]
请详细描述遇到的问题

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Agniyz ***@***.***>
Sent: Saturday, December 30, 2023 12:03:19 AM
To: ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin] 部署后58913端口无法访问？ (Issue #54)

        - External Email -



―

**Comment by Agniyz** [comment]
官方的部署运行之后可以通过58913端口进行网页访问管理audiobot，但linux整合包部署后无法访问，是因为整合包没有WebInterface文件夹吗？

**Comment by ZHANGTIANYAO1** [comment]
没有支持网页的计划

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Agniyz** [comment]
好的了解了

**Comment by XuVIIJay** [comment]
为什么刚部署好的时候可以打开58913控制网站，后来不行了，我是Ubuntu搭建的。目前网易云api能正常打开，!api token也有反应，但是点不了歌了。求大佬帮助

**Comment by ZHANGTIANYAO1** [comment]
就像项目描述所说该项目已经停止维护了，请移步新项目

**Comment by XuVIIJay** [comment]
大佬新的这个项目网页UI写的真的很好，很想用上这个BOT。我是用的方法二手动安装，!play 歌名有反应，网页也能显示歌曲，但是一直卡着不播放，这是我运行时的提示和start_log文件。不知道是不是之前部署的的ffmpeg在这里冲突了还是什么情况。


         原始邮件
         
       
发件人：TIANYAO ZHANG ***@***.***&gt;
发件时间：2026年3月31日 21:45
收件人：ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin ***@***.***&gt;
抄送：XuVIIJay ***@***.***&gt;, Comment ***@***.***&gt;
主题：Re: [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin] 部署后58913端口无法访问？ (Issue #54)



ZHANGTIANYAO1 left a comment (ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin#54)

就像项目描述所说该项目已经停止维护了，请移步新项目

**Comment by ZHANGTIANYAO1** [comment]
请在新项目的issue中提交，同时，没有看到你的运行时的提示和start_log文件
