### ISSUE TITLE
本地部署网易云api后音乐机器人添加歌单报错 : The remote server returned an error: (406) Not Acceptable.

### ISSUE THREAD

**Issue by Daieenbo** [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin#58]
目前机器人单曲播放正常 部分歌单可以正常播放 另有部分歌单添加时会产生下放报错
例如这个歌单 https://music.163.com/#/playlist?id=8756933204
![image](https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/assets/67773252/b9c84c5d-68bf-45fd-8a49-5608a052e424)
![image](https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/assets/67773252/5c777d84-4886-4a71-8696-8ac9e1733cd0)

插件配置如图  Api正常启动 可看到提示网页；机器人也是正常启动 可以进入后台
![屏幕截图 2024-01-05 145434](https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/assets/67773252/0a45a41f-ba13-4b1f-9e5b-8b0960b7f48f)

**Comment by Purestone** [comment]
请问是如何解决的呢
