### ISSUE TITLE
不懂编译哪位大佬提供arm64 liux的打包，或者有好朋友提供下编译思路。

### ISSUE THREAD

**Issue by lauren12133** [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin#60]
我得编译环境是liux
编译必须是net3.1还是说随便向下兼容的.net版本就行
需要修改项目的哪些地方

**Comment by 1048632280** [comment]
release往下拉，1.1.0版本里有TS3Bot.linux-x64.zip，是已经编译好的bot

**Comment by lauren12133** [comment]
> release往下拉，1.1.0版本里有TS3Bot.linux-x64.zip，是已经编译好的bot

环境alpine
ffmpg已经安装
下载liux x64  
赋予执行权限
运行失败 提示not found
是否还需要其他依赖库 
尝试通关安装./net7
dotnet TS3AudioBot 也是提示报错
请问该项目需要特殊的运行方式？

**Comment by 1048632280** [comment]
> > release往下拉，1.1.0版本里有TS3Bot.linux-x64.zip，是已经编译好的bot
> 
> 环境alpine ffmpg已经安装 下载liux x64 赋予执行权限 运行失败 提示not found 是否还需要其他依赖库 尝试通关安装./net7 dotnet TS3AudioBot 也是提示报错 请问该项目需要特殊的运行方式？

有具体报错信息吗？我记得赋予执行权限后，直接执行./TS3AudioBot就可以运行了

**Comment by lauren12133** [comment]
> > > release往下拉，1.1.0版本里有TS3Bot.linux-x64.zip，是已经编译好的bot
> > 
> > 
> > 环境alpine ffmpg已经安装 下载liux x64 赋予执行权限 运行失败 提示not found 是否还需要其他依赖库 尝试通关安装./net7 dotnet TS3AudioBot 也是提示报错 请问该项目需要特殊的运行方式？
> 
> 有具体报错信息吗？我记得赋予执行权限后，直接执行./TS3AudioBot就可以运行了

root@Debian:~/tsbot/linux-x64# ./TS3AudioBot 
No usable version of libssl was found
Aborted

**Comment by 1048632280** [comment]
> alpine

这个是因为缺少libssl库，也可能是版本不匹配，需要libssl版本为1.0.
根据你的Linux系统下载libssl1.0，比如Ubuntu在http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.0/

**Comment by lauren12133** [comment]
> libssl1.0

libssl-dev is already the newest version (3.0.11-1~deb12u2).   3.0了都

**Comment by 1048632280** [comment]
> > libssl1.0
> 
> libssl-dev 已经是最新版本 （3.0.11-1~deb12u2）。3.0了都

不是，他必须要1.0版本，你要再装一个

**Comment by lauren12133** [comment]
> > > libssl1.0
> > 
> > 
> > libssl-dev 已经是最新版本 （3.0.11-1~deb12u2）。3.0了都
> 
> 不是，他必须要1.0版本，你要再装一个

我这debian12 新的openssl库还不能让我装低版本的libssl

**Comment by 1048632280** [comment]
> > > > libssl1.0
> > > 
> > > 
> > > libssl-dev 已经是最新版本 （3.0.11-1~deb12u2）。3.0了都
> > 
> > 
> > 不是，他必须要1.0版本，你要再装一个
> 
> 我这debian12 新的openssl库还不能让我装低版本的libssl

我没有用过Debian，也没其他方法解决这个问题，可以考虑Ubuntu或者降低系统版本

**Comment by FiveHair** [comment]
@lauren12133 试试我fork的版本？https://github.com/FiveHair/TS3AudioBot-NetEaseCloudmusic-plugin-UNM

**Comment by lauren12133** [comment]
> @lauren12133 试试我fork的版本？https://github.com/FiveHair/TS3AudioBot-NetEaseCloudmusic-plugin-UNM

继续使用该项目的打包  替换你的[plugin]是吗

**Comment by FiveHair** [comment]
> > @lauren12133 试试我fork的版本？https://github.com/FiveHair/TS3AudioBot-NetEaseCloudmusic-plugin-UNM
> 
> 继续使用该项目的打包 替换你的[plugin]是吗

是的，Linux应该没问题，但是ARM我没有设备没测试过。

**Comment by lauren12133** [comment]
> > > @lauren12133 试试我fork的版本？https://github.com/FiveHair/TS3AudioBot-NetEaseCloudmusic-plugin-UNM
> > 
> > 
> > 继续使用该项目的打包 替换你的[plugin]是吗
> 
> 是的，Linux应该没问题，但是ARM我没有设备没测试过。

arm还得单独编译吧 我不懂编译 先x64试试吧

**Comment by FiveHair** [comment]
> > > > @lauren12133 试试我fork的版本？https://github.com/FiveHair/TS3AudioBot-NetEaseCloudmusic-plugin-UNM
> > > 
> > > 
> > > 继续使用该项目的打包 替换你的[plugin]是吗
> > 
> > 
> > 是的，Linux应该没问题，但是ARM我没有设备没测试过。
> 
> arm还得单独编译吧 我不懂编译 先x64试试吧

你可以试试docker版的ts3audiobot

**Comment by lauren12133** [comment]
> > > > > @lauren12133 试试我fork的版本？https://github.com/FiveHair/TS3AudioBot-NetEaseCloudmusic-plugin-UNM
> > > > 
> > > > 
> > > > 继续使用该项目的打包 替换你的[plugin]是吗
> > > 
> > > 
> > > 是的，Linux应该没问题，但是ARM我没有设备没测试过。
> > 
> > 
> > arm还得单独编译吧 我不懂编译 先x64试试吧
> 
> 你可以试试docker版的ts3audiobot
我现在用的就是主线docker的arm 但是这个项目里不是说用主线bot会报错吗 你得不会吗
//使用官方构建的ts3aduiobot会报错，因为官方的编译环境有问题。
解决方法：1.自行构建 2.使用我打包的版本
重复卸载加载插件会出现问题，如果需要重新加载请先重启Bot//

**Comment by FiveHair** [comment]
> > > > > > @lauren12133 试试我fork的版本？https://github.com/FiveHair/TS3AudioBot-NetEaseCloudmusic-plugin-UNM
> > > > > 
> > > > > 
> > > > > 继续使用该项目的打包 替换你的[plugin]是吗
> > > > 
> > > > 
> > > > 是的，Linux应该没问题，但是ARM我没有设备没测试过。
> > > 
> > > 
> > > arm还得单独编译吧 我不懂编译 先x64试试吧
> > 
> > 
> > 你可以试试docker版的ts3audiobot
> > 我现在用的就是主线docker的arm 但是这个项目里不是说用主线bot会报错吗 你得不会吗
> > //使用官方构建的ts3aduiobot会报错，因为官方的编译环境有问题。
> > 解决方法：1.自行构建 2.使用我打包的版本
> > 重复卸载加载插件会出现问题，如果需要重新加载请先重启Bot//

我自用的就是主线的docker，可以正常使用
![image](https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/assets/16514929/09069c3f-0a8d-488e-b6f5-dfa09ae0c21d)

**Comment by lauren12133** [comment]
> > > > > > > @lauren12133 试试我fork的版本？https://github.com/FiveHair/TS3AudioBot-NetEaseCloudmusic-plugin-UNM
> > > > > > 
> > > > > > 
> > > > > > 继续使用该项目的打包 替换你的[plugin]是吗
> > > > > 
> > > > > 
> > > > > 是的，Linux应该没问题，但是ARM我没有设备没测试过。
> > > > 
> > > > 
> > > > arm还得单独编译吧 我不懂编译 先x64试试吧
> > > 
> > > 
> > > 你可以试试docker版的ts3audiobot
> > > 我现在用的就是主线docker的arm 但是这个项目里不是说用主线bot会报错吗 你得不会吗
> > > //使用官方构建的ts3aduiobot会报错，因为官方的编译环境有问题。
> > > 解决方法：1.自行构建 2.使用我打包的版本
> > > 重复卸载加载插件会出现问题，如果需要重新加载请先重启Bot//
> 
> 我自用的就是主线的docker，可以正常使用 ![image](https://private-user-images.githubusercontent.com/16514929/296121014-09069c3f-0a8d-488e-b6f5-dfa09ae0c21d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMzE1MzEsIm5iZiI6MTcwNTAzMTIzMSwicGF0aCI6Ii8xNjUxNDkyOS8yOTYxMjEwMTQtMDkwNjljM2YtMGE4ZC00ODhlLWI2ZjUtZGZhMDlhZTBjMjFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDAzNDcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1OWE1MWViZDYzMTY1OTVhNTkxYjRmZTkzNDMwNWI3NmY5NjE5MWQ1ODdjZjE2NWNhYzM5YzU2NDhmZDhjZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c96K4PwG1dvH36W7eLwMIix46aAtyh-0G-q3A78M9po)
好的谢谢 我的开发板用的也是这位的镜像  我去试试

**Comment by FiveHair** [comment]
> > > > > > > > @lauren12133 试试我fork的版本？https://github.com/FiveHair/TS3AudioBot-NetEaseCloudmusic-plugin-UNM
> > > > > > > 
> > > > > > > 
> > > > > > > 继续使用该项目的打包 替换你的[plugin]是吗
> > > > > > 
> > > > > > 
> > > > > > 是的，Linux应该没问题，但是ARM我没有设备没测试过。
> > > > > 
> > > > > 
> > > > > arm还得单独编译吧 我不懂编译 先x64试试吧
> > > > 
> > > > 
> > > > 你可以试试docker版的ts3audiobot
> > > > 我现在用的就是主线docker的arm 但是这个项目里不是说用主线bot会报错吗 你得不会吗
> > > > //使用官方构建的ts3aduiobot会报错，因为官方的编译环境有问题。
> > > > 解决方法：1.自行构建 2.使用我打包的版本
> > > > 重复卸载加载插件会出现问题，如果需要重新加载请先重启Bot//
> > 
> > 
> > 我自用的就是主线的docker，可以正常使用 ![image](https://private-user-images.githubusercontent.com/16514929/296121014-09069c3f-0a8d-488e-b6f5-dfa09ae0c21d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMzE1MzEsIm5iZiI6MTcwNTAzMTIzMSwicGF0aCI6Ii8xNjUxNDkyOS8yOTYxMjEwMTQtMDkwNjljM2YtMGE4ZC00ODhlLWI2ZjUtZGZhMDlhZTBjMjFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDAzNDcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1OWE1MWViZDYzMTY1OTVhNTkxYjRmZTkzNDMwNWI3NmY5NjE5MWQ1ODdjZjE2NWNhYzM5YzU2NDhmZDhjZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c96K4PwG1dvH36W7eLwMIix46aAtyh-0G-q3A78M9po)
> > 好的谢谢 我的开发板用的也是这位的镜像  我去试试

把/app/data 映射出来，在里面新建plugins文件夹，把插件的dll和ini扔进去，把ini配置一下就可以

**Comment by lauren12133** [comment]
> > > > > > > > > @lauren12133 试试我fork的版本？https://github.com/FiveHair/TS3AudioBot-NetEaseCloudmusic-plugin-UNM
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 继续使用该项目的打包 替换你的[plugin]是吗
> > > > > > > 
> > > > > > > 
> > > > > > > 是的，Linux应该没问题，但是ARM我没有设备没测试过。
> > > > > > 
> > > > > > 
> > > > > > arm还得单独编译吧 我不懂编译 先x64试试吧
> > > > > 
> > > > > 
> > > > > 你可以试试docker版的ts3audiobot
> > > > > 我现在用的就是主线docker的arm 但是这个项目里不是说用主线bot会报错吗 你得不会吗
> > > > > //使用官方构建的ts3aduiobot会报错，因为官方的编译环境有问题。
> > > > > 解决方法：1.自行构建 2.使用我打包的版本
> > > > > 重复卸载加载插件会出现问题，如果需要重新加载请先重启Bot//
> > > 
> > > 
> > > 我自用的就是主线的docker，可以正常使用 ![image](https://private-user-images.githubusercontent.com/16514929/296121014-09069c3f-0a8d-488e-b6f5-dfa09ae0c21d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMzE1MzEsIm5iZiI6MTcwNTAzMTIzMSwicGF0aCI6Ii8xNjUxNDkyOS8yOTYxMjEwMTQtMDkwNjljM2YtMGE4ZC00ODhlLWI2ZjUtZGZhMDlhZTBjMjFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDAzNDcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1OWE1MWViZDYzMTY1OTVhNTkxYjRmZTkzNDMwNWI3NmY5NjE5MWQ1ODdjZjE2NWNhYzM5YzU2NDhmZDhjZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c96K4PwG1dvH36W7eLwMIix46aAtyh-0G-q3A78M9po)
> > > 好的谢谢 我的开发板用的也是这位的镜像  我去试试
> 
> 把/app/data 映射出来，在里面新建plugins文件夹，把插件的dll和ini扔进去，把ini配置一下就可以

Error: Unknown Teamspeak Error. (Missing teamspeak permissions.) (b_client_modify_own_description)   !yun login这个报错

**Comment by FiveHair** [comment]
机器人权限给了吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月12日(周五) 下午3:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin] 不懂编译哪位大佬提供arm64 liux的打包，或者有好朋友提供下编译思路。 (Issue #60)




          
@lauren12133 试试我fork的版本？https://github.com/FiveHair/TS3AudioBot-NetEaseCloudmusic-plugin-UNM
  
继续使用该项目的打包 替换你的[plugin]是吗
  
是的，Linux应该没问题，但是ARM我没有设备没测试过。
  
arm还得单独编译吧 我不懂编译 先x64试试吧
  
你可以试试docker版的ts3audiobot
 我现在用的就是主线docker的arm 但是这个项目里不是说用主线bot会报错吗 你得不会吗
 //使用官方构建的ts3aduiobot会报错，因为官方的编译环境有问题。
 解决方法：1.自行构建 2.使用我打包的版本
 重复卸载加载插件会出现问题，如果需要重新加载请先重启Bot//
   
我自用的就是主线的docker，可以正常使用 
 好的谢谢 我的开发板用的也是这位的镜像  我去试试
   
把/app/data 映射出来，在里面新建plugins文件夹，把插件的dll和ini扔进去，把ini配置一下就可以
  
Error: Unknown Teamspeak Error. (Missing teamspeak permissions.) (b_client_modify_own_description)   !yun login这个报错

**Comment by lauren12133** [comment]
> 机器人权限给了吗
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年1月12日(周五) 下午3:40 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin] 不懂编译哪位大佬提供arm64 liux的打包，或者有好朋友提供下编译思路。 (Issue #60) @lauren12133 试试我fork的版本？https://github.com/FiveHair/TS3AudioBot-NetEaseCloudmusic-plugin-UNM 继续使用该项目的打包 替换你的[plugin]是吗 是的，Linux应该没问题，但是ARM我没有设备没测试过。 arm还得单独编译吧 我不懂编译 先x64试试吧 你可以试试docker版的ts3audiobot 我现在用的就是主线docker的arm 但是这个项目里不是说用主线bot会报错吗 你得不会吗 //使用官方构建的ts3aduiobot会报错，因为官方的编译环境有问题。 解决方法：1.自行构建 2.使用我打包的版本 重复卸载加载插件会出现问题，如果需要重新加载请先重启Bot// 我自用的就是主线的docker，可以正常使用 好的谢谢 我的开发板用的也是这位的镜像 我去试试 把/app/data 映射出来，在里面新建plugins文件夹，把插件的dll和ini扔进去，把ini配置一下就可以 Error: Unknown Teamspeak Error. (Missing teamspeak permissions.) (b_client_modify_own_description) !yun login这个报错 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

你得意思是进docker容器下 手动给机器人权限？

**Comment by FiveHair** [comment]
https://github.com/Splamy/TS3AudioBot?tab=readme-ov-file#first-time-setup 需要给ts3bot配置权限的

**Comment by lauren12133** [comment]
> https://github.com/Splamy/TS3AudioBot?tab=readme-ov-file#first-time-setup 需要给ts3bot配置权限的 @lauren12133

好了都弄好了 谢谢
