### ISSUE TITLE
虚拟化环境机器人部署后无法正常点歌、登录账号

### ISSUE THREAD

**Issue by Daieenbo** [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin#61]
![image](https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/assets/67773252/d4f46e63-1d4c-4522-854e-2c29b0e40cf6)
如图 已经本地部署网易云API且正确加载
如有能帮忙解决的请联系QQ: 1905420439

**Comment by ZHANGTIANYAO1** [comment]
请上传完整日志文件log

**Comment by Daieenbo** [comment]
[ts3audiobot_2024-01-17_14_21_28.log](https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/files/13973529/ts3audiobot_2024-01-17_14_21_28.log)
这份可以吗

**Comment by ZHANGTIANYAO1** [comment]
所有歌曲都是这样吗

**Comment by ZHANGTIANYAO1** [comment]
设置文件打开截个图

**Comment by ZHANGTIANYAO1** [comment]
.ini

**Comment by Daieenbo** [comment]
是的 所有用到插件的指令都没有办法正常运作 提示URI PREFIX无法解析

**Comment by Daieenbo** [comment]
![image](https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/assets/67773252/c1acbc68-c3a5-4a1a-bbd4-d2ed7226aceb)

**Comment by ZHANGTIANYAO1** [comment]
API地址改成http://127.0.0.1:3000试试

**Comment by Daieenbo** [comment]
好的我试试
