### ISSUE TITLE
ssl问题无法连接

### ISSUE THREAD

**Issue by btrencai** [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin#63]
An unexpected error occurred: The SSL connection could not be established, see inner exception. The remote certificate is invalid according to the validation procedure.

**Comment by btrencai** [comment]
插件运行后使用!yun xxx指令，均会显示这个

**Comment by btrencai** [comment]
linux服务器搭建

**Comment by ZHANGTIANYAO1** [comment]
检查服务器和网易云API的防火墙

**Comment by ZHANGTIANYAO1** [comment]
是docker部署的吗

**Comment by ZHANGTIANYAO1** [comment]
回复错位置了
目前默认的api地址不可用

**Comment by btrencai** [comment]
回复错地方了，抱歉，不知是不是bug，linux服务器中他的配置文件地址为/www/wwwroot/ts3music/data/plugins/，和插件不是同一个文件夹，缺失会报错

**Comment by ZHANGTIANYAO1** [comment]
正常现象

**Comment by btrencai** [comment]
好滴，麻烦啦

**Comment by btrencai** [comment]
大佬，机器人不显示音乐图片是为什么
