### ISSUE TITLE
用Windows Server 2022搭建的ts3机器人输入!yun login 头像显示不出来

### ISSUE THREAD

**Issue by Whv1olet** [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin#66]
![bd9c3418835af6898ab962245d4eb88](https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/assets/158094803/48742d4a-f973-4299-a9d8-90183208cd78)
就像这样

**Comment by Whv1olet** [comment]
![Uploading 微信图片_20240130034636.png…]()

**Comment by XuXian9930** [comment]
请提供客户端日志

**Comment by Whv1olet** [comment]
![4de6a5c78bc5bc333b1ec73de90b159](https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/assets/158094803/1d4def42-224f-4c07-9e6c-820451db88e7)

**Comment by Whv1olet** [comment]
> 请提供客户端日志

![4de6a5c78bc5bc333b1ec73de90b159](https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/assets/158094803/87151e0a-e901-4525-a242-5e2b0efeba08)

**Comment by Whv1olet** [comment]
> 能提供完整的日志吗
![367a917aa3cfac59d07a40ec0f14acd](https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/assets/158094803/33093574-e481-4938-9379-a98937392f1f)

**Comment by XuXian9930** [comment]
你可以右键全选以复制所有log

**Comment by Whv1olet** [comment]
> 你可以右键全选以复制所有log

2024/1/29 19:33:06		Info	TeamSpeak Client 3.6.2 (2023-09-20 09:48:13)	
2024/1/29 19:33:06		Info	SystemInformation: Windows 11 (22621) x64 (AMD or Intel) Binary: 64bit	
2024/1/29 19:33:06	Windows Audio Session	Devel	Hardware agc available and enabled. - Microphone (Lenovo X370)	
2024/1/29 19:33:06	Windows Audio Session	Devel	Hardware agc not available - 麦克风 (DroidCam Virtual Audio)	
2024/1/29 19:33:06	Windows Audio Session	Devel	Hardware agc not available - AI Noise-Canceling Microphone (ASUS Utility)	
2024/1/29 19:33:06	Windows Audio Session	Devel	Hardware agc not available - Virtual Microphone (ASUS Utility)	
2024/1/29 19:33:06	SoundDevManager	Debug	Loading dynamic soundbackend from C:/Program Files/TeamSpeak 3 Client/soundbackends/directsound_win64.dll	
2024/1/29 19:33:06	Direct Sound	Debug	setting timer resolution to 1ms - 	
2024/1/29 19:33:06	SoundDevManager	Debug	Soundbackend loaded.	
2024/1/29 19:33:06	ClientUI	Info	OpenGL Info: LibGLES, Vendor: Google Inc., Renderer: ANGLE (AMD Radeon RX590 GME Direct3D11 vs_5_0 ps_5_0), Version: OpenGL ES 2.0 (ANGLE 2.1.0.57ea533f79a7)	
2024/1/29 19:33:06		Info	*** Time [ICONMANGER]: 104	
2024/1/29 19:33:06	Addons	Info	Checking for addon updates...	
2024/1/29 19:33:06	Plugins	Info	Loading plugin: clientquery_plugin_win64.dll	
2024/1/29 19:33:06	Query	Info	listening on 127.0.0.1:25639	
2024/1/29 19:33:06	Plugins	Info	Loading plugin: gamepad_joystick_win64.dll	
2024/1/29 19:33:06	Plugins	Info	Loading plugin: teamspeak_control_plugin_win64.dll	
2024/1/29 19:33:06	Gamepad Plugin	Info	Found client raw input wnd proc	
2024/1/29 19:33:06	Gamepad Plugin	Info	Cleared device list	
2024/1/29 19:33:06	ControlPlugin	Info	Control Plugin started, accepting connections	
2024/1/29 19:33:06	Windows Audio Session	Devel	DeviceDeleteList::wait_for_deletes - enter - DeviceDeleteList	
2024/1/29 19:33:06	Windows Audio Session	Devel	DeviceDeleteList::wait_for_deletes - leave - DeviceDeleteList	
2024/1/29 19:33:06		Info	*** Time [BUILD_GUI]: 168	
2024/1/29 19:33:06		Info	*** Time [SERVERVIEW]: 193	
2024/1/29 19:33:06		Info	*** Time [SERVERVIEWMANAGER]: 204	
2024/1/29 19:33:06		Info	*** Time [MAINWINDOW]: 605	
2024/1/29 19:33:06		Info	*** Time [INIT]: 605	
2024/1/29 19:33:06	ClientUI	Info	Qt version: 5.15.2	
2024/1/29 19:33:06	ClientUI	Info	Using configuration location: C:\Users\lyl23\AppData\Roaming\TS3Client\settings.db	
2024/1/29 19:33:06	Addon	Info	Addon up to date.	
2024/1/29 19:33:07	ClientUI	Info	Last update check was: 周二 1月 30 02:36:41 2024	
2024/1/29 19:33:07		Info	Statistics report: Not yet, next report on 周一 2月 19 12:07:20 2024	
2024/1/29 19:33:07	Bookmarks	Info	Collecting autoconnect bookmarks	
2024/1/29 19:33:07	Newsticker	Info	Newsticker next check: 周二 1月 30 21:32:12 2024	
2024/1/29 19:33:08		Info	disconnected from push system.	
2024/1/29 19:33:08	ClientUI	Info	Connect to server: 114.132.218.138	
2024/1/29 19:33:08	ClientUI	Info	Initiating connection: 114.132.218.138:9987	
2024/1/29 19:33:08	Windows Audio Session	Devel	DeviceDeleteList::wait_for_deletes - enter - DeviceDeleteList	
2024/1/29 19:33:08	Windows Audio Session	Devel	DeviceDeleteList::wait_for_deletes - leave - DeviceDeleteList	
2024/1/29 19:33:08	Windows Audio Session	Debug	WAS::openDevice-enter - {0.0.0.00000000}.{8e38c045-831d-4df3-8735-1447864abcca}	
2024/1/29 19:33:08	Windows Audio Session	Devel	Mix Format: SRate:48000 Bitrate: 32 Channels: 2 - 扬声器 (Lenovo X370)	
2024/1/29 19:33:08	Windows Audio Session	Devel	Initializing with mix format. - 扬声器 (Lenovo X370)	
2024/1/29 19:33:08	Windows Audio Session	Info	Initialized with 2 channels in 32bit, 48kHz. - 扬声器 (Lenovo X370)	
2024/1/29 19:33:08	Windows Audio Session	Devel	WAS Buffer size: 1056 - 扬声器 (Lenovo X370)	
2024/1/29 19:33:08	Windows Audio Session	Debug	WAS::openDevice-leave - {0.0.0.00000000}.{8e38c045-831d-4df3-8735-1447864abcca}	
2024/1/29 19:33:08	Windows Audio Session	Debug	WAS::startDevice-enter - {0.0.0.00000000}.{8e38c045-831d-4df3-8735-1447864abcca}	
2024/1/29 19:33:08	Windows Audio Session	Debug	WAS::startDevice-leave - {0.0.0.00000000}.{8e38c045-831d-4df3-8735-1447864abcca}	
2024/1/29 19:33:08	Windows Audio Session	Devel	DeviceDeleteList::wait_for_deletes - enter - DeviceDeleteList	
2024/1/29 19:33:08	Windows Audio Session	Devel	DeviceDeleteList::wait_for_deletes - leave - DeviceDeleteList	
2024/1/29 19:33:08	Windows Audio Session	Debug	WAS::openDevice-enter - {0.0.1.00000000}.{196a0555-9fa5-4535-b926-5fbaed7b5871}	
2024/1/29 19:33:08	Windows Audio Session	Devel	Mix Format: SRate:48000 Bitrate: 32 Channels: 1 - Microphone (Lenovo X370)	
2024/1/29 19:33:08	Windows Audio Session	Devel	Initializing with mix format. - Microphone (Lenovo X370)	
2024/1/29 19:33:08	Windows Audio Session	Info	Initialized with 1 channels in 32bit, 48kHz. - Microphone (Lenovo X370)	
2024/1/29 19:33:08	Windows Audio Session	Devel	WAS Buffer size: 1056 - Microphone (Lenovo X370)	
2024/1/29 19:33:08	Windows Audio Session	Debug	WAS::openDevice-leave - {0.0.1.00000000}.{196a0555-9fa5-4535-b926-5fbaed7b5871}	
2024/1/29 19:33:08	Windows Audio Session	Debug	WAS::startDevice-enter - {0.0.1.00000000}.{196a0555-9fa5-4535-b926-5fbaed7b5871}	
2024/1/29 19:33:08	Windows Audio Session	Debug	WAS::startDevice-leave - {0.0.1.00000000}.{196a0555-9fa5-4535-b926-5fbaed7b5871}	
2024/1/29 19:33:08	ClientUI	Info	Connect status: Connecting	
2024/1/29 19:33:08	PktHandler	Info	server sent ciphers:1	
2024/1/29 19:33:08	PktHandler	Info	Selected cipher:0	
2024/1/29 19:33:08	PktHandler	Devel	Puzzle solve time: 3	
2024/1/29 19:33:08	ClientUI	Info	Connect status: Connected	
2024/1/29 19:33:08	ClientUI	Info	Connect status: Establishing connection	
2024/1/29 19:33:08	ClientUI	Info	Connect status: Connection established	
2024/1/29 19:33:08		Info	connected to push system.	
2024/1/29 19:33:08	Addon	Info	Addon up to date.	
2024/1/29 19:33:10	Addon	Info	Addon up to date.	
2024/1/29 19:33:30	ClientUI	Info	Request already running, aborting avatar request	
2024/1/29 19:33:30	ClientUI	Info	Request already running, aborting avatar request	
2024/1/29 19:35:49	ClientUI	Info	Request already running, aborting avatar request	
2024/1/29 19:40:28	ClientUI	Info	Request already running, aborting avatar request	
2024/1/29 19:41:27	ClientUI	Info	Request already running, aborting avatar request	
2024/1/29 19:44:29	ClientUI	Info	Request already running, aborting avatar request	
2024/1/29 19:48:06		Info	Memory usage: 113.71 MiB	
2024/1/29 20:00:23	UIHelpers	Info	Supported image formats: *.bmp *.gif *.jpeg *.jpg *.pbm *.pgm *.png *.ppm *.svg *.svgz *.webp *.xbm *.xpm	
2024/1/29 20:00:27	ClientUI	Info	Avatar file size check: 1 200000	
2024/1/29 20:01:34	ClientUI	Info	Request already running, aborting avatar request	
2024/1/29 20:01:50	ClientUI	Info	Request already running, aborting avatar request	
2024/1/29 20:03:06		Info	Memory usage: 210.45 MiB	
2024/1/29 20:05:06	ClientUI	Info	Request already running, aborting avatar request

**Comment by XuXian9930** [comment]
疑似是服务端端口未开放引起的
TeamSpeak 默认情况下, 服务器端需要下表中的端口
|端口|协议|说明|
|:---:|:---:|:---:|
|9987|UDP|默认语音服务器端口|
|10011|TCP|ServerQuery raw 端口|
|10022|TCP|ServerQuery SSH 端口(需要 3.3.0 以上版本服务端)|
|10080|TCP|ServerQuery HTTP 端口(需要 3.12.0 以上版本服务端)|
|10443|TCP|ServerQuery HTTPS 端口(需要 3.12.0 以上版本服务端)|
|30033|TCP|文件传输端口|
|41144|TCP|TSDNS|

**Comment by Whv1olet** [comment]
> 疑似是服务端端口未开放引起的 TeamSpeak 默认情况下, 服务器端需要下表中的端口
> 
> 端口	协议	说明
> 9987	UDP	默认语音服务器端口
> 10011	TCP	ServerQuery raw 端口
> 10022	TCP	ServerQuery SSH 端口(需要 3.3.0 以上版本服务端)
> 10080	TCP	ServerQuery HTTP 端口(需要 3.12.0 以上版本服务端)
> 10443	TCP	ServerQuery HTTPS 端口(需要 3.12.0 以上版本服务端)
> 30033	TCP	文件传输端口
> 41144	TCP	TSDNS
解决了，我把你发的这些端口都开放了
谢谢大佬
