### ISSUE TITLE
音频播放时有异常声音

### ISSUE THREAD

**Issue by mouyase** [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin#69]
https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/assets/7844572/992eab98-0174-462a-944d-123156b6cacf

上面是频道里的录音，看了一下CPU网络内存都没跑满，应该不是硬件配置的问题。
搭建是Ubuntu22.04下，使用docker，teamspeak3官方镜像+ancieque/ts3audiobot的bot镜像(这个镜像是官方在readme里写的)。

想知道问题是出在哪的。

**Comment by ZHANGTIANYAO1** [comment]
插件本身不会产生噪音，请排查其他原因
