### ISSUE TITLE
使用gedanid导入歌单时报错An unexpected error occurred: '{' is invalid after a single JSON value. Expected end of data. Path: $ | LineNumber: 0 | BytePositionInLine: 33.

### ISSUE THREAD

**Issue by cuki-QAQ** [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin#71]

**Comment by ZHANGTIANYAO1** [comment]
请上传日志

**Comment by cuki-QAQ** [comment]
日志也只有这一条：19:00:47.4164|ERROR|0| Unexpected command error: '{' is invalid after a single JSON value. Expected end of data. Path: $ | LineNumber: 0 | BytePositionInLine: 33.
![image](https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/assets/120362640/4edc4b51-f435-4448-bb8a-cd331059a738)
不过我前几天更换歌单的时候似乎发现了问题所在。歌单内歌曲数超过1000的时候会出现此报错 更换其它歌曲数小于1000的歌单的时候是可以正常使用的

**Comment by ZHANGTIANYAO1** [comment]
此错误为网易云api的问题，部分非本地的网易云api无法返回过大的歌单列表。因此请自行本地部署
