### ISSUE TITLE
卡巴斯基报毒

### ISSUE THREAD

**Issue by Epxir** [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin#72]
![image](https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/assets/79371047/2bf35ef6-dc8f-46d3-8889-132bf4ec1db7)

**Comment by ZHANGTIANYAO1** [comment]
此项目仅为TS3AudioBot的网易云插件，如果有安全方面的疑问，请找该项目的作者反馈。
