### ISSUE TITLE
 INFO|0|PlayManager.StopInternal Song queue ended: No next song could be played.

### ISSUE THREAD

**Issue by xyha1** [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin#73]
无论我播放什么音乐都会返回这个错误。不管是歌曲名字还是歌单id。我的平台是centos8，用的整合包里audiobot+插件。

**Comment by xyha1** [comment]
INFO|0|PlayManager.StopInternal Song queue ended: No next song could be played.

**Comment by ZHANGTIANYAO1** [comment]
检查一下网易云API是否正常工作

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: xyha1 ***@***.***>
发送时间: Sunday, March 24, 2024 9:29:04 AM
收件人: ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin] INFO|0|PlayManager.StopInternal Song queue ended: No next song could be played. (Issue #73)

        - External Email -



INFO|0|PlayManager.StopInternal Song queue ended: No next song could be played.

―
