### ISSUE TITLE
播放经常卡顿爆音

### ISSUE THREAD

**Issue by hulinhao233** [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin#77]
播放播放经常卡顿爆音，严重的时候是一个一个音放出来的，服务器音质设置最大，bot播放音质才设置到40，ts服务器跑下载文件可以跑15mbps，不知道为什么放个歌放不动，应该不是网络问题

**Comment by ZHANGTIANYAO1** [comment]
bot播放音质需要调大，太小容易产生问题
