### ISSUE TITLE
网易云API指令出错 Unexpected command error: 不知道这样的主机。 不知道这样的主机。

### ISSUE THREAD

**Issue by Peterseer** [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin#79]
bot能顺利加入语音，TS3能正常打开，网易云API配置在本地部署。
使用的是Release中的整合包
能正常加载plugins，在使用任何!yun指令时报错 17:40:58.0248|ERROR|0| Unexpected command error: 不知道这样的主机。 不知道这样的主机。

**Comment by ZHANGTIANYAO1** [comment]
检查一下权限设置

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: PeterseerZhang ***@***.***>
发送时间: Sunday, May 26, 2024 5:44:13 PM
收件人: ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin ***@***.***>
抄送: Subscribed ***@***.***>
主题: [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin] 网易云API指令出错 Unexpected command error: 不知道这样的主机。 不知道这样的主机。 (Issue #79)

        - External Email -



bot能顺利加入语音，TS3能正常打开，网易云API配置在本地部署。
使用的是Release中的整合包
能正常加载plugins，在使用任何!yun指令时报错 17:40:58.0248|ERROR|0| Unexpected command error: 不知道这样的主机。 不知道这样的主机。

―

**Comment by ZHANGTIANYAO1** [comment]
或者是api部署不正确

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Zhang Tianyao ***@***.***>
发送时间: Sunday, May 26, 2024 5:46:22 PM
收件人: ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin ***@***.***>; ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin] 网易云API指令出错 Unexpected command error: 不知道这样的主机。 不知道这样的主机。 (Issue #79)

检查一下权限设置

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: PeterseerZhang ***@***.***>
发送时间: Sunday, May 26, 2024 5:44:13 PM
收件人: ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin ***@***.***>
抄送: Subscribed ***@***.***>
主题: [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin] 网易云API指令出错 Unexpected command error: 不知道这样的主机。 不知道这样的主机。 (Issue #79)

        - External Email -



bot能顺利加入语音，TS3能正常打开，网易云API配置在本地部署。
使用的是Release中的整合包
能正常加载plugins，在使用任何!yun指令时报错 17:40:58.0248|ERROR|0| Unexpected command error: 不知道这样的主机。 不知道这样的主机。

―

**Comment by Peterseer** [comment]
权限没问题，可以用TS3播放本地音频，网易云API本地部署网页可访问。仍需解决。

**Comment by Peterseer** [comment]
已发现是API端口有误，已解决。
