### ISSUE TITLE
非管理员不能私聊bot点歌，报错

### ISSUE THREAD

**Issue by SnowCaNNN** [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin#81]
我是管理员可以用指令，但是朋友不行，用指令后bot报错Error: You cannot execute 'yun play'. You are missing the 'cmd.yun.play' right!

**Comment by WuyanLuoxi** [comment]
@SnowCaNNN 你好，我也遇到了这个问题，请问你解决了么?

**Comment by ZHANGTIANYAO1** [comment]
权限设置问题

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
