### ISSUE TITLE
加载插件!plugin load 0无效

### ISSUE THREAD

**Issue by lazywoo** [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin#84]
查看日志信息
15:00:25.3484| WARN|0| Plugin "YunBot.cs" [0] compiler notifications:
Error L13/C18: The type or namespace name 'Json' does not exist in the namespace 'System.Text' (are you missing an assembly reference?)
看起来是某个版本的某个依赖不对
如何解决？😭

**Comment by lazywoo** [comment]
ubuntu 22 
dotnet 8.0.105

**Comment by ZHANGTIANYAO1** [comment]
ubuntu 推荐使用docker
