### ISSUE TITLE
关于teamspeak中机器人登录命令的错误

### ISSUE THREAD

**Issue by Kiko-sys** [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin#88]
为什么!yun login命令
<16:17:54> "Betsy":
cpu: 0%
memory: 130MB
startime: 9/18/2024 8:14:25 AM 我输了命令之后没有出现二维码 而是cpu信息和时间

**Comment by Kevinwu901113** [comment]
先!plugin load 0加载插件
