### ISSUE TITLE
无法播放歌单

### ISSUE THREAD

**Issue by NightRaidz** [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin#93]
使用id或者名字都无法播放歌单，单曲没问题。
11:33:59.2662|ERROR|0| Unexpected command error: '{' is invalid after a single JSON value. Expected end of data. Path: $ | LineNumber: 0 | BytePositionInLine: 33.
以及这个bot可以循环播放吗，我设置了顺序循环也只播放一遍。

**Comment by ZHANGTIANYAO1** [comment]
使用在线的网易云api有长度限制，歌单过大会报错，循环播放需要列表中有2首或以上的音乐

**Comment by NightRaidz** [comment]
好的，感谢回复
