### ISSUE TITLE
其他人无法使用指令点歌

### ISSUE THREAD

**Issue by NightRaidz** [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin#94]
我修改了right.toml文件，
# Playing rights
[[rule]]
	# Set Group Ids you want to allow here, ex: [ 13, 42 ]
	# groupid = []
	# And/Or Client Uids here, ex [ "uA0U7t4PBxdJ5TLnarsOHQh4/tY=", "8CnUQzwT/d9nHNeUaed0RPsDxxk=" ]
	#  useruid = [""]
	# Or remove groupid and useruid to allow for everyone
将groupid和useid都注释掉了，其他人还是不能使用指令

**Comment by ZHANGTIANYAO1** [comment]
https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/issues/44
