### ISSUE TITLE
使用!yun play点歌后每首歌都要播放两次

### ISSUE THREAD

**Issue by SnowRain1326** [ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin#95]
使用命令后一次性会把同一首歌添加两次到歌单里

**Comment by ZHANGTIANYAO1** [comment]
用的什么版本的插件？

**Comment by ZHANGTIANYAO1** [comment]
播放模式是什么

**Comment by SnowRain1326** [comment]
播放模式是0 插件是用的[增强](https://github.com/ZHANGTIANYAO1/TS3AudioBot-NetEaseCloudmusic-plugin/pull/68)

**Comment by ZHANGTIANYAO1** [comment]
需要去对应pr下提issue

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
